# Generated by Django 4.0.2 on 2022-02-28 21:03

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('sets', models.IntegerField(default=4)),
                ('repetitions', models.IntegerField(default=12)),
                ('duration', models.FloatField(blank=True, default=0)),
                ('rest_period', models.FloatField(blank=True, default=0)),
                ('direction', models.CharField(blank=True, choices=[('1', 'HORIZONTAL'), ('2', 'VERTICAL')], max_length=2, null=True)),
                ('target', models.CharField(blank=True, choices=[('1', 'LOWER'), ('2', 'UPPER'), ('3', 'CORE')], max_length=2, null=True)),
                ('level', models.CharField(blank=True, choices=[('1', 'BEGINNER'), ('2', 'INTERMEDIATE'), ('3', 'ADVANCE')], max_length=2, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('public', models.BooleanField(default=False)),
                ('copy_only', models.BooleanField(default=False)),
                ('preset', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Superset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('public', models.BooleanField(default=False)),
                ('copy_only', models.BooleanField(default=False)),
                ('preset', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'supersets',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('exercises', models.ManyToManyField(blank=True, related_name='workouts', to='builder.Exercise')),
                ('supersets', models.ManyToManyField(blank=True, related_name='workouts', to='builder.Superset')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
