# Generated by Django 4.0.2 on 2022-02-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='uuid',
            new_name='id',
        ),
    ]
