# Generated by Django 4.0.2 on 2022-03-02 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_alter_exercise_repetitions_alter_exercise_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
