# Generated by Django 4.0.2 on 2022-03-02 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_exercise_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='supersets',
        ),
        migrations.AddField(
            model_name='superset',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supersets', to='builder.workout'),
        ),
    ]
