# Generated by Django 4.0.2 on 2022-03-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_remove_workout_supersets_superset_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='cardio_unit',
            field=models.CharField(blank=True, choices=[('1', 'METERS'), ('2', 'KILOMETERS')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='repetitions_unit',
            field=models.CharField(blank=True, choices=[('1', 'REPS'), ('2', 'UNTIL FAILURE'), ('3', 'SECONDS'), ('4', 'MINUTES')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='resistance_view',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('1', 'KILOGRAMS'), ('3', 'POUNDS')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.CharField(blank=True, choices=[('1', 'BEGINNER'), ('2', 'INTERMEDIATE'), ('3', 'ADVANCE')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='target',
            field=models.CharField(blank=True, choices=[('1', 'LOWER'), ('2', 'UPPER'), ('3', 'CORE')], max_length=3, null=True),
        ),
    ]
