# Generated by Django 4.0.2 on 2022-03-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_exercise_cardio_unit_exercise_repetitions_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='cardio_unit',
            field=models.CharField(blank=True, choices=[('1', 'METERS'), ('2', 'KILOMETERS')], default='1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='repetitions_unit',
            field=models.CharField(blank=True, choices=[('1', 'REPS'), ('2', 'UNTIL FAILURE'), ('3', 'SECONDS'), ('4', 'MINUTES')], default='1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('1', 'KILOGRAMS'), ('3', 'POUNDS')], default='1', max_length=2, null=True),
        ),
    ]
