# Generated by Django 4.0.2 on 2022-03-10 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_alter_exercise_cardio_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='distance',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.FloatField(blank=True, default=30),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='repetitions',
            field=models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rest_period',
            field=models.FloatField(blank=True, default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.FloatField(blank=True, default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
