# Generated by Django 4.0.2 on 2022-02-28 21:46

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builder', '0003_rename_uuid_workout_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercises', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('completed', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='builder.workout')),
            ],
        ),
        migrations.CreateModel(
            name='SessionSuperset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('exercises', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_supersets', to='workout_session.workoutsession')),
            ],
        ),
    ]
