# Generated by Django 4.0.2 on 2022-02-28 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout_session', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutsession',
            old_name='completed',
            new_name='supersets',
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SessionSuperset',
        ),
    ]
