# Generated by Django 4.0.2 on 2022-02-28 22:23

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_session', '0002_rename_completed_workoutsession_supersets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='exercises',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='supersets',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
