# Generated by Django 4.0.2 on 2022-03-01 07:35

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workout_session', '0003_alter_workoutsession_exercises_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSuperset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('exercises', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='supersets',
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('sets', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='workout_session.workoutsession')),
            ],
        ),
    ]
