# Generated by Django 4.0.2 on 2022-03-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_session', '0004_sessionsuperset_remove_workoutsession_exercises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexercise',
            name='rest_period',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
