# Generated by Django 4.0.2 on 2022-03-01 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_session', '0005_sessionexercise_rest_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsuperset',
            name='workout_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_supersets', to='workout_session.workoutsession'),
        ),
    ]
